insert into tb_category(name, created_At) values ('Books', NOW())
insert into tb_category(name, created_At) values ('Electronics', NOW())
insert into tb_category(name, created_At) values ('Computers', NOW())
insert into tb_category(name, created_At) values ('Clothes', NOW())
insert into tb_category(name, created_At) values ('Hair', NOW())
insert into tb_category(name, created_At) values ('Make Up', NOW())
insert into tb_category(name, created_At) values ('Beauty', NOW())
insert into tb_category(name, created_At) values ('Stationary Store', NOW())
insert into tb_category(name, created_At) values ('Shoes', NOW())
insert into tb_category(name, created_At) values ('Food', NOW())
insert into tb_category(name, created_At) values ('Nail Polishes', NOW())
insert into tb_category(name, created_At) values ('Glasses', NOW())
insert into tb_category(name, created_At) values ('Drinks', NOW())
